export const QUESTIONS = [
  "Misafir ağırlamaktan hoşlanırım.",
  "Evcil hayvanlarla yaşamayı severim.",
  "Düzenli bir ev ortamı benim için çok önemlidir.",
  "Gece geç saatlere kadar uyanık kalmayı tercih ederim.",
  "Ortak alanlarda sessizliğe önem veririm.",
  "Evde sık sık parti veya etkinlik düzenlemeyi severim.",
  "Ev işlerini planlı bir şekilde bölüşmek isterim.",
  "Ev arkadaşımla yakın arkadaş olmayı beklerim.",
  "Ortak harcamalar için ortak bir kasa oluşturmayı tercih ederim.",
  "Kişisel alanıma çok saygı duyulmasını isterim.",
  "Yemeklerimi genellikle evde kendim yaparım.",
  "Evde müzik dinlerken veya film izlerken hoparlör kullanırım.",
  "Hafta sonları genelde evde vakit geçirmeyi severim.",
  "Ev arkadaşımın misafirlerinin kalıya kalmasından rahatsız olmam.",
  "Temizlik konusunda oldukça titizimdir.",
  "Gündelik hayatta spontane planlar yapmayı severim.",
  "Eşyalarımın benden habersiz kullanılmasından rahatsız olurum.",
  "Evin sıcaklığının genelde yüksek olmasını tercih ederim.",
  "Sigara/nargile gibi alışkanlıklara karşı hassasiyetim vardır.",
  "Evin ortak alanlarında kişisel eşya bırakılmasını sevmem.",
  "Fatura ve kiraların günü gününe ödenmesi konusunda çok hassasım.",
  "Ev arkadaşımla beraber yemek yemeyi veya aktivite yapmayı severim.",
  "Çalışma veya eğitim saatlerim oldukça düzenlidir.",
  "Evde bitki yetiştirmekten veya bakmaktan hoşlanırım.",
  "Gürültülü komşulara karşı toleransım düşüktür."
];
